# active-msg - mensagem de ativação que aparece para o player quando ele utiliza /luz.
# deactive-msg - mensagem de desativação que aparece para o player quando ele utiliza /luz.

active-msg: '&a A LUZ FOI ATIVADA!'
deactive-msg: '&c A LUZ FOI DESATIVADA!'